### ISSUE TITLE
Admin Title Used in Breadcrumb

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#231]
Currently the admin title is being used for the breadcrumb.  We need to change to the display title.

**Comment by drmyers1** [comment]
@rjbain could you take a look at this dev request?

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 Not sure how this can be done, looks like a real hassle. I'd suggest switching the fields, that is, keeping the title as display title and then changing current display title to admin title. We can change the content view to display admin titles instead of display (regular) titles.

**Comment by drmyers1** [comment]
@mjuarez2 i was hoping it was going to easy.  the problem is that we have been using the field as the admin title.

**Comment by rjbain** [comment]
@drmyers1 Could you take a look here?
https://pr-251-dgreat.pantheonsite.io/

Also added the current page to the breadcrumbs which was missing before.

**Comment by drmyers1** [comment]
@rjbain this looks like you fixed it.

**Comment by rjbain** [comment]
Merging

Rob Bain
Web Developer
University of San Francisco
Web Services
