### ISSUE TITLE
Top Apps and Quick Links

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#247]
We need to add a link under the top tabs to return to the dashboard.  Also, do we currently have caching on the dashboard for the these features.  If so, how long is it set for?

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 This is on https://pr-250-dgreat.pantheonsite.io

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 Quick Links and Fav Apps currently have 30 minute caching set on the block view for the dashboard

**Comment by drmyers1** [comment]
@mjuarez2 this looks good.

**Comment by nicholas-kebbas** [comment]
@drmyers1 @mjuarez2 So it looks like the caching applies when you re-order, but not when you add/remove quick links or top apps.  

Also I believe the scope for the top apps was to originally not allow the user to unflag.  If they unflag, since they're unable to access the all apps page, they can never get it back. @mjuarez2 could you remove the unflag this item option for the Top Apps (not the quick links)

**Comment by nicholas-kebbas** [comment]
@mjuarez2 Looks good now thanks Michael

**Comment by drmyers1** [comment]
@mjuarez2 looks good.

**Comment by drmyers1** [comment]
@mjuarez2 it seems the return to dashboard links for the top apps and links are showing up for all roles.  Can you please look at this again?

**Comment by mjuarez2** [comment]
@drmyers1 Set caching to none on the blocks so maybe try again on https://pr-256-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 this looks to be working

**Comment by nicholas-kebbas** [comment]
@mjuarez2 looks good to me
